language: node_js
node_js:
- '0.8'
before_script:
- npm install -g mocha
- npm install -g bower
- npm install
script: bower install -f -V; mocha --recursive --reporter list
notifications:
  email:
    on_failure: change
deploy:
  provider: s3
  access_key_id: 0188XPHDQN9BTPGHGG02
  secret_access_key:
    secure: YZR9QTtOk0P9HH8NbC06VJJZ64eANlEi24JbUYX3Z66OJ+GWUxUDbfBeRU+vhsCCTWC/eOe1FElQcrGk8b56uY2KRtCI31BYeHDLhaipu4vm4S4JnA2+eCqlSsc8jLLwxv3lxRXlP2NCkpjL7dUlnjRPIFQGc3aJYVn+Pzj3Yc0=
  bucket: rodrigoi
  local-dir: src
  upload-dir: game-of-life-backbonejs
  skip_cleanup: true
  on:
    repo: rodrigoi/game-of-life-backbonejs
